version: "3.9"

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - VITE_BACKEND_URL=http://backend:5000
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5240"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - JWT_SECRET=1234567891234567891234567891234567
      - LOCAL_CONNECTION_STRING=Host=db;Port=5432;Database=evently;Username=postgres;Password=naruto95
    volumes:
      - ./server/firebase/serviceAccountKey.json:/app/firebase/serviceAccountKey.json:ro
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: evently_test_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: naruto95
      POSTGRES_DB: evently
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
